Repository wechaty/docusaurus, pull requests merged in 2021-09, with the labels that each got.

#1231 Rust-Wechaty
  docusaurus/docs/polyglot/rust/overview.md
Labels: GSoD 2021, references

#929 [GSoD 2021] Added blogs on gRPC and OpenAPI
  jekyll/_posts/2021-06-08-design-and-document-apis-with-swagger.md
  jekyll/_posts/2021-06-08-introduction-to-grpc.md
  jekyll/assets/2021/06-design-and-document-apis-with-swagger/1.webp
  jekyll/assets/2021/06-design-and-document-apis-with-swagger/2.webp
  jekyll/assets/2021/06-design-and-document-apis-with-swagger/3.webp
  jekyll/assets/2021/06-introduction-to-grpc/1.webp
  jekyll/assets/2021/06-introduction-to-grpc/2.webp
Labels: GSoD 2021, improve the grpc and openapi ecosystem

#1008 [GSoD 2021] Wrapped the string literals in a JSX container
  docusaurus/src/pages/press.tsx
Labels: GSoD 2021

#1014 [GSoD 2021] Added Progressive Web Application (PWA) support for the Jekyll blog
  jekyll/Gemfile
  jekyll/_config.yml
  jekyll/_layouts/default.html
  jekyll/assets/pwa/android/android-launchericon-144-144.webp
  jekyll/assets/pwa/android/android-launchericon-192-192.webp
  jekyll/assets/pwa/android/android-launchericon-48-48.webp
  jekyll/assets/pwa/android/android-launchericon-512-512.webp
  jekyll/assets/pwa/chrome/chrome-extensionmanagementpage-48-48.webp
  jekyll/assets/pwa/chrome/chrome-favicon-16-16.webp
  jekyll/assets/pwa/chrome/chrome-installprocess-128-128.webp
  jekyll/assets/pwa/firefox/firefox-general-128-128.webp
  jekyll/assets/pwa/firefox/firefox-general-16-16.webp
  jekyll/assets/pwa/firefox/firefox-general-48-48.webp
  jekyll/assets/pwa/firefox/firefox-marketplace-512-512.webp
  jekyll/manifest.json
  jekyll/service-worker.js
Labels: GSoD 2021, improve the grpc and openapi ecosystem

#1209 [How to Guides] MID TERM BLOG
  jekyll/_posts/2021-08-13-gsod-mid-term-how-to-guide-blog.md
  jekyll/assets/2021/08-gsod-mid-term-how-to-guide-blog/gsod-2021.webp
Labels: GSoD 2021, how to guide

#1251 Add missing badges to Heartbeat plugin page
  docusaurus/docs/using-plugin-with-wechaty/heartbeat.mdx
Labels: GSoD 2021, tutorials

#1250 Add missing badges to Event Logger plugin page
  docusaurus/docs/using-plugin-with-wechaty/event-logger.mdx
Labels: GSoD 2021, tutorials

#1249 Add video demo of ding ding bot
  docusaurus/docs/tutorials/overview.md
Labels: GSoD 2021, tutorials

#1057 Update the Python-Wechaty
  docusaurus/docs/polyglot/python/overview.md
Labels: GSoD 2021, references

#1212 Update Puppet Providers service
  docusaurus/docs/puppet-providers/service.md
Labels: GSoD 2021, references, ready to merge

#869 Updated team proposal for How to Guide
  jekyll/_posts/2021-05-12-gsod-2021-how-to-guide-team-proposal.md
Labels: GSoD 2021

#1100 The .NET Wechaty
  docusaurus/docs/polyglot/dotnet/overview.md
Labels: GSoD 2021, references, ready to merge

#913 added wechaty-class section
  docusaurus/docs/api/wechaty-class.md
Labels: GSoD 2021, references

#1211 Update Puppet Providers Wechat 4u
  docusaurus/docs/puppet-providers/wechat4u.md
Labels: GSoD 2021, references, ready to merge

#919 Added Wechaty token section
  docusaurus/docs/specs/gateway.mdx
Labels: GSoD 2021, references, ready to merge

#1195 Update Puppet Providers padlocal
  docusaurus/docs/puppet-providers/padlocal.md
  docusaurus/static/img/docs/puppet-providers/padlocal-topological-graph.webp
Labels: GSoD 2021, references, ready to merge

#1107 Update Puppet Providers overview
  docusaurus/docs/puppet-providers/overview.mdx
Labels: GSoD 2021, references

#1208 Update References official account
  docusaurus/docs/puppet-providers/official-account.md
Labels: GSoD 2021, references

#1156 The PHP-Wechaty
  docusaurus/docs/polyglot/php/overview.md
Labels: GSoD 2021, references

#873 What can you do with Wechaty sub-section of Introduction section
  docusaurus/docs/what-can-you-do-with-wechaty.md
  docusaurus/sidebars.ts
Labels: GSoD 2021, introduction

#1252 Update order of language display
  docusaurus/docs/polyglot/transclusions/shortest-chatbots.mdx
Labels: GSoD 2021, tutorials

#1254 Updated links in tutorials overview page and removed empty pages from examples section
  docusaurus/docs/examples/advanced/demo-in-tutorial.md
  docusaurus/docs/examples/advanced/gist-bot.md
  docusaurus/docs/examples/professional/api-ai-bot.md
  docusaurus/docs/examples/professional/blessed-twins-bot.md
  docusaurus/docs/examples/professional/hot-import-bot.md
  docusaurus/docs/examples/professional/monster-bot.md
  docusaurus/docs/examples/professional/speech-to-text-bot.md
  docusaurus/docs/examples/professional/telegram-roger-bot.md
  docusaurus/docs/tutorials/cheatsheet.md
  docusaurus/docs/tutorials/overview.md
  docusaurus/sidebars.ts
Labels: GSoD 2021, tutorials

#1253 Added missing badges to QR code terminal plugin
  docusaurus/docs/using-plugin-with-wechaty/qr-code-terminal.mdx
Labels: GSoD 2021, tutorials

#1207 Tutorial for tuling123 bot
  docusaurus/docs/examples/professional/tuling123-bot.md
  docusaurus/docs/examples/professional/tuling123-bot.mdx
  docusaurus/docs/tutorials/overview.md
Labels: GSoD 2021, tutorials

#947 How to guide overview
  docusaurus/docs/howto/overview.mdx
Labels: GSoD 2021, how to guide

#871 What is Wechaty sub-section of the Introduction section
  docusaurus/docs/wechaty.md
  docusaurus/docs/wechaty.mdx
Labels: GSoD 2021, introduction, ready to merge

#958 Customise bot
  docusaurus/docs/howto/event.md
  docusaurus/static/img/docs/howto/event/package-json.webp
Labels: GSoD 2021, how to guide

#1261 Updated the API references overview section
  docusaurus/docs/api/overview.mdx
Labels: GSoD 2021, references

#1096 Scala-Wechaty
  docusaurus/docs/polyglot/scala/overview.md
Labels: GSoD 2021, references

#1013 Week-7 Wechaty Polyglot
  docusaurus/docs/polyglot/overview.mdx
Labels: GSoD 2021, references

#1233 Added Polyglot Architecture image
  docusaurus/static/img/polyglot-architecure.webp
Labels: GSoD 2021, references

#916 Added the wechaty-message references section
  docusaurus/docs/api/message.md
Labels: GSoD 2021, references

#1110 Update Puppet Providers - Gitter
  docusaurus/docs/puppet-providers/gitter.md
Labels: GSoD 2021, references

#910 [GSoD 2021] Added Progressive Web Application (PWA) support for the Docusaurus site
  docusaurus/docusaurus.config.js
  docusaurus/static/img/pwa/android/android-launchericon-144-144.webp
  docusaurus/static/img/pwa/android/android-launchericon-192-192.webp
  docusaurus/static/img/pwa/android/android-launchericon-48-48.webp
  docusaurus/static/img/pwa/android/android-launchericon-512-512.webp
  docusaurus/static/img/pwa/chrome/chrome-extensionmanagementpage-48-48.webp
  docusaurus/static/img/pwa/chrome/chrome-favicon-16-16.webp
  docusaurus/static/img/pwa/chrome/chrome-installprocess-128-128.webp
  docusaurus/static/img/pwa/firefox/firefox-general-128-128.webp
  docusaurus/static/img/pwa/firefox/firefox-general-16-16.webp
  docusaurus/static/img/pwa/firefox/firefox-general-48-48.webp
  docusaurus/static/img/pwa/firefox/firefox-marketplace-512-512.webp
  docusaurus/static/manifest.json
  package.json
Labels: GSoD 2021, improve the grpc and openapi ecosystem

#889 [GSoD 2021] Added Open Graph image metadata in the docusaurus site of wechaty.js.org
  docusaurus/docusaurus.config.js
Labels: GSoD 2021, improve the grpc and openapi ecosystem

#972 Week-6 Updated the puppet.md file
  docusaurus/docs/specs/puppet.md
  docusaurus/static/img/docs/messageprocess-flow.webp
Labels: GSoD 2021, references, ready to merge

#1140 Deploy in Padlocal
  docusaurus/docs/howto/deploy-padlocal.mdx
  docusaurus/static/img/docs/howto/IM_platform/PadLocal.webp
Labels: GSoD 2021, how to guide

#1265 Updated room-invitation section
  docusaurus/docs/api/room-invitation.md
Labels: GSoD 2021, references

#1106 [How to guides] Whatsapp section
  docusaurus/docs/howto/deploy-whatsapp.md
  docusaurus/static/img/docs/howto/deploy-whatsapp/deploy-whatsapp.webp
Labels: GSoD 2021, how to guide

#1154 Gitter section
  docusaurus/docs/howto/deploy-gitter.mdx
  docusaurus/docs/howto/overview.mdx
  docusaurus/static/img/docs/howto/deploy-gitter/wechaty-puppet-gitter.webp
  package.json
Labels: GSoD 2021, how to guide

#1141 Deploy in wechat4u
  docusaurus/docs/howto/deploy-wechat4u.mdx
  docusaurus/docs/howto/overview.mdx
  docusaurus/static/img/docs/howto/IM_platform/wechat4u.webp
  docusaurus/static/img/docs/howto/deploy-wechat4u/wechat4u.webp
  package.json
Labels: GSoD 2021, how to guide

#1136 Deploy in WeChat official account
  docusaurus/docs/howto/overview.mdx
  docusaurus/docs/howto/wechat-offical.mdx
  docusaurus/static/img/docs/howto/IM_platform/wechaty-official-account.webp
  docusaurus/static/img/docs/howto/wechat-offical/wechaty-official-account.webp
  package.json
Labels: GSoD 2021, how to guide

#1098 Deploy in WeChat
  docusaurus/docs/howto/deploy-wechat.mdx
  docusaurus/docs/howto/overview.mdx
  docusaurus/static/img/docs/howto/IM_platform/deploy-wechat.webp
  docusaurus/static/img/docs/howto/deploy-wechat/deploy-wechat.webp
  package.json
Labels: GSoD 2021, how to guide

#1040 [How to guides] Deploying with Heroku
  docusaurus/docs/howto/heroku.md
  docusaurus/docs/howto/overview.mdx
  docusaurus/static/img/howto/heroku/heroku.webp
  docusaurus/static/img/howto/heroku/heroku1.webp
  docusaurus/static/img/howto/heroku/heroku2.webp
  docusaurus/static/img/howto/heroku/heroku3.webp
  package.json
Labels: GSoD 2021, how to guide

#1028 Deployment with Docker
  docusaurus/docs/howto/docker.mdx
  docusaurus/docs/howto/overview.mdx
  docusaurus/sidebars.ts
  package.json
Labels: GSoD 2021, how to guide

#1050 Updated the Go-Wechaty
  docusaurus/docs/polyglot/go/overview.md
Labels: GSoD 2021, references, ready to merge

#1148 Improve tutorials running locally page
  docusaurus/docs/getting-started/running-locally.mdx
  docusaurus/static/img/docs/getting-started/running-locally/bot-demo.png
  docusaurus/static/img/docs/getting-started/running-locally/bot-demo.webp
  docusaurus/static/img/docs/getting-started/running-locally/hard-way.png
  docusaurus/static/img/docs/getting-started/running-locally/hard-way.webp
Labels: GSoD 2021, tutorials

#1108 Update Puppet Providers : wechat
  docusaurus/docs/puppet-providers/wechat.md
Labels: GSoD 2021, references

#1220 Usage Puppet Providers Mock
  docusaurus/docs/puppet-providers/mock.md
Labels: GSoD 2021, references

#1022 Send and receive files
  docusaurus/docs/howto/file-box.mdx
  docusaurus/docs/howto/overview.mdx
  package.json
Labels: GSoD 2021, how to guide

#1278 Puppet services padlocal
  docusaurus/docs/puppet-services/padlocal.md
  docusaurus/static/img/docs/references/puppet-services/padlocal/architecture.webp
  docusaurus/static/img/docs/references/puppet-services/padlocal/qrcode.webp
  docusaurus/static/img/docs/references/puppet-services/padlocal/step-1-terminal.webp
  docusaurus/static/img/docs/references/puppet-services/padlocal/step-1.webp
Labels: GSoD 2021, references

#1236 Ospp interim report matrix appservice wechaty
  jekyll/_posts/2021-08-30-ospp-mid-term-matrix-wechaty.md
  jekyll/assets/2021/08-ospp-mid-term-matrix-wechaty/report-ppt.pdf
  jekyll/assets/2021/08-ospp-mid-term-matrix-wechaty/wechaty-matrix.webp
  package.json
Labels: ospp

#1284 Add Puppet Services FAQ
  docusaurus/docs/puppet-services/faq.md
  docusaurus/sidebars.ts
Labels: GSoD 2021, references

#1228 OSPP 2021: mid-term report of wechaty-cli
  jekyll/_posts/2021-08-26-ospp-mid-term-cli.md
  jekyll/assets/2021/08-ospp-mid-term-cli/mid-slides.pdf
  jekyll/assets/2021/08-ospp-mid-term-cli/terminal-wechaty.webp
Labels: ospp

#1285 Add Puppet Services Wxwork
  docusaurus/docs/puppet-services/wxwork.md
Labels: GSoD 2021, references

#1277 Puppet services overview
  docusaurus/docs/getting-started/overview.mdx
  docusaurus/docs/puppet-services/overview.mdx
  docusaurus/docs/puppet-services/tokens.md
  docusaurus/sidebars.ts
Labels: GSoD 2021, references

#1294 Updated the Room section in API references
  docusaurus/docs/api/room.md
Labels: GSoD 2021, references

#1289 Update the friendship class section
  docusaurus/docs/api/friendship.md
Labels: GSoD 2021, references

#1290 Update contacts in API references
  docusaurus/docs/api/contact.md
Labels: GSoD 2021, references

#1283 Updated the Polyglot Do it yourself section
  docusaurus/docs/polyglot/diy/overview.md
Labels: GSoD 2021, references

#1276 [GSoD 2021] Improved contributing guidelines
  docusaurus/docs/contributing/blog.md
  docusaurus/docs/contributing/code-of-conduct.md
  docusaurus/docs/contributing/contributor-program.md
  docusaurus/docs/contributing/devops.md
  docusaurus/docs/contributing/documentation.md
  docusaurus/docs/contributing/getting-help.md
  docusaurus/docs/contributing/git.md
  docusaurus/docs/contributing/new-contributors.md
  docusaurus/docs/contributing/overview.md
  docusaurus/docs/contributing/pulls.md
  docusaurus/sidebars.ts
Labels: GSoD 2021, improve the grpc and openapi ecosystem

#1298 Fix CodeSandbox link of Ding Dong Bot
  docusaurus/docs/examples/basic/ding-dong-bot.md
Labels: GSoD 2021, tutorials

#1286 Update Main references overview
  docusaurus/docs/references/overview.mdx
Labels: GSoD 2021, references

#1235 Mid Term blog of OSPP 2021: Wechaty Puppet Official Account
  jekyll/_posts/2021-08-26-ospp-mid-term-wechaty-puppet-oa.md
  jekyll/assets/2021/08-ospp-mid-term-wechaty-puppet-oa/wechaty-puppet-oa-midterm-ppt.pdf
  jekyll/assets/2021/08-ospp-mid-term-wechaty-puppet-oa/wechaty-puppet-official-account.webp
Labels: ospp

#930 Software Development Kit subsection of the Explanations section
  docusaurus/docs/explanations/sdk-cui.md
  docusaurus/sidebars.ts
Labels: GSoD 2021, explanation, ready to merge

#915 Overview subsection of the explanation section
  docusaurus/docs/explanations/overview.mdx
  docusaurus/sidebars.ts
Labels: GSoD 2021, explanation, ready to merge

#1234 initial OSPP 2021 Mid-Term Itchat Puppet
  jekyll/_posts/2021-08-29-ospp-mid-term-wechaty-itchat-puppet.md
  jekyll/assets/2021/08-ospp-mid-term-wechaty-itchat-puppet/itchat.pdf
  jekyll/assets/2021/08-ospp-mid-term-wechaty-itchat-puppet/python-wechaty-puppet-itchat.webp
Labels: ospp

#1273 changed the side label for resolving the left bar navigation
  docusaurus/docs/specs/gateway.mdx
  docusaurus/sidebars.ts
Labels: GSoD 2021, references

#1241 Midreport-lark-puppet
  jekyll/_posts/2021-08-30-ospp-mid-term-wechaty-puppet-lark.md
  jekyll/assets/2021/08-ospp-mid-term-wechaty-puppet-lark/mid-term-ppt.pdf
  jekyll/assets/2021/08-ospp-mid-term-wechaty-puppet-lark/wechaty-lark.webp
Labels: ospp

#964 Manage contact
  docusaurus/docs/howto/contact.mdx
  docusaurus/docs/howto/overview.mdx
  package.json
Labels: GSoD 2021, how to guide

#949 Add DevOps sub-section of the explanation section
  docusaurus/docs/explanations/devops-toolset.md
  docusaurus/sidebars.ts
  docusaurus/static/img/docs/explanations/devops-toolset/chatie-devops-toolset.webp
  docusaurus/static/img/docs/explanations/devops-toolset/chatie-eslint-config.webp
  docusaurus/static/img/docs/explanations/devops-toolset/chatie-git-scripts.webp
  docusaurus/static/img/docs/explanations/devops-toolset/chatie-semver.webp
  docusaurus/static/img/docs/explanations/devops-toolset/chatie-tsconfig.webp
  docusaurus/static/img/docs/explanations/devops-toolset/pkg-jq.webp
  docusaurus/static/img/docs/explanations/devops-toolset/tstest.webp
Labels: GSoD 2021, explanation, ready to merge

#1279 Update puppet services compatibility
  docusaurus/docs/puppet-services/compatibility.md
Labels: GSoD 2021, references

#1242 OSPP 2021-期中报告-开发支持 QQ 聊天软件的 Wechaty Puppet Provider 模块
  jekyll/_posts/2021-08-31-ospp-mid-term-qq-puppet.md
  jekyll/assets/2021/08-ospp-mid-term-qq-puppet/qq-puppet.pdf
  jekyll/assets/2021/08-ospp-mid-term-qq-puppet/wechaty-qq-puppet-logo.webp
  package.json
Labels: ospp

#1310 changed the heading to lower case
  docusaurus/docs/references/overview.mdx
Labels: GSoD 2021, references
